Enhancements for ManagedObnjectController
stablekernel/aqueduct pull request #773
Opened 2020-01-28 15:20 UTC by Reductions

- [x] Allow scope authorization to be used for the different actions.
-- [x] Implement the feature
-- [x] Add test
- [ ] Add possibility to used `accept`, `ignore`, `reject` and `require` when the body is read in `PUT` and `POST` actions.
-- [] Implement the feature
-- [] Add tests

2020-01-28 15:31 UTC, itsjoeconway requested changes

2020-01-28 15:31 UTC, joeconwaystk commented on aqueduct/lib/src/http/managed_object_controller.dart
> +    if (scopes != null) {
Can you change this to ```if (scopes == null) { 
  return; 
}```

2020-01-28 15:31 UTC, joeconwaystk commented on aqueduct/lib/src/http/managed_object_controller.dart
> +        throw Response.serverError();
It'd be good to log (severe or error?) this situation since it'd be hard to debug otherwise.

2020-01-28 15:31 UTC, joeconwaystk commented on aqueduct/lib/src/http/managed_object_controller.dart
> +      if (!AuthScope.verify(
Can you extract the result of this boolean expression to a variable to make it more readable?

2020-01-28 15:31 UTC, joeconwaystk commented on aqueduct/test/http/subclass_managed_object_controller_with_scopes_test.dart
> +  List<String> get findObjectWithIdScopes => ['get'];
Can you provide a test scenario for the empty and multiple cases of acceptable scope?

2020-01-28 15:31 UTC, joeconwaystk commented on aqueduct/lib/src/http/managed_object_controller.dart
> +  List<String> get createNewObjectScopes => null;
I think there is a better interface to this feature than these 5 separate overridable fields for two reasons. 

1. You can use the ManagedObjectController without subclassing (and this is the intended use case).
2. The five separate fields seem dispersed... collapsing them into a single structure that has similar properties might work (e.g. `controller.scopes.create = [...]`)

2020-01-28 15:32 UTC, joeconwaystk commented
Good feature add, some small feedback items and it should be good to go. Love the tests!

2020-01-28 15:40 UTC, Reductions commented on aqueduct/lib/src/http/managed_object_controller.dart
> +  List<String> get createNewObjectScopes => null;
Good suggestion!
Would you be OK if I put then as optional field(fields) in the  constructor?

2020-01-28 15:49 UTC, joeconwaystk commented on aqueduct/lib/src/http/managed_object_controller.dart
> +  List<String> get createNewObjectScopes => null;
I think that makes sense, as long as it doesn't create a breaking change where existing managed object controller subclasses require a non-default constructor.

2020-01-29 00:42 UTC, Reductions commented
I may split the second part in a different pull request (The one about being able to filter the body decode for `POST` and `PUT`).

2020-08-27 15:52 UTC, closed without merging